---
- name: verify consul service is running and reachable from localhost
  command: "{{ consul_home }}/bin/consul info"
  register: _consul_info
  until: _consul_info.rc == 0
  retries: 6
  delay: 4
  changed_when: false
